### ISSUE TITLE
Deprecated Errors

### ISSUE THREAD

**Issue by ruivenda** [atom-material/atom-material-syntax#48] opened 2017-01-11 14:30 UTC
Latest upgrade of Atom break the theme with deprecated status.

Any change of this being solved?

Deprecated selectors! Both in the theme ui and the theme syntax

**Comment by lowmess** [comment] 2017-01-11 21:25
The 'Report Issue' button in Atom leads to a 414 error, but this is the error in question:

> `atom-material-syntax/index.less`
> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
> ...bunch of `selector` => `updated-selector` lines...
> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lowmess** [comment] 2017-01-11 21:27
oops! looks like this is actually a dupe of #45

**Comment by silvestreh** [comment] 2017-01-12 13:50
Closing this one in favor of #45

**Closed by silvestreh** 2017-01-12 13:50 UTC
